### ISSUE TITLE
switch.rainbird became unavalible

### ISSUE THREAD

**Issue by kotana** [konikvranik/hacs_rainbird#11]
Hi,
have the following problem,
that the switches are sporadically no longer available...
Sometimes when I want to turn the sprinklers on and off, they stop responding.

![image](https://user-images.githubusercontent.com/760382/185987271-b6631ed0-4df8-4df3-83ea-a7da56dfe56d.png)

![image](https://user-images.githubusercontent.com/760382/185985072-3314ae21-6ae8-474e-a2c0-35f531d091b1.png)

![image](https://user-images.githubusercontent.com/760382/185987748-0dbfebd7-f8c4-441f-b9a7-2608b69a2afe.png)

**Comment by konikvranik** [comment]
I never observed such behavior. How to reproduce this?

**Comment by kotana** [comment]
As I said before, I had the normal rainbird integration running and it worked.
But it's been a long time.
Both integrations are currently not working properly.
The sprinklers are recognized but are intermittently unavailable or respond incorrectly or with a delay.

Should I maybe set the ESP RZEXe Rainbird to factory settings?
I haven't tried that yet.
The behavior is really weird.
I don't know what else to do and the Rainbird app sucks.

**Comment by konikvranik** [comment]
@kotana : Can you provide the logs at least?

**Comment by kotana** [comment]
Sorry I'm late.
It's been dealt with.
The problem was with my router.
Everything works again.
Thanks again.
