### ISSUE TITLE
Use of unique_id in this or native component

### ISSUE THREAD

**Issue by filmgarage** [konikvranik/hacs_rainbird#13]
Is this the development version of the native component in HA core?

It seems like this version is supporting the unique_id for entities (I am definitely missing that more than a UI install. Would it be possible to bring the unique_id to the native component?

**Comment by konikvranik** [comment]
Hi. this is not official component of the home assistant.
I created the original component, but I don't have time comply all the strict development rules in the core, so I forked it to thic unofficial component and if I need to add something I add it here quicky.

But feel free to incorporate these changes into official component. Anybody can do this.
