### ISSUE TITLE
No UI showing for Rainbird

### ISSUE THREAD

**Issue by jeremy-mattern** [konikvranik/hacs_rainbird#3]
I have installed and downloaded this repository using HACS, and restarted homeassistant.  

When I go into the homeassistant integrations, I do not find a rainbird option to configure it. Is it listed under a different name?

Thanks!

JM

**Comment by jeremy-mattern** [comment]
This resolved with an update of HACS. Now there is a new error, see thread containing error: "Error
Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble"

**Comment by konikvranik** [comment]
Currently the pyrainbird library is broken: https://github.com/jbarrancos/pyrainbird/issues/38

**Comment by konikvranik** [comment]
I forked the pyrainbird library to alternative one. So current version of hacs_raibird works ok with pyrainbird-alternative:5.4.0

**Comment by ziliotti** [comment]
Hello, at the moment I have the same problem signaled by jeremy-mattern in february. Home Assistant, HACS and everything else have been updated to the last version. After installing the integration with HACS and restarting HA, the rain bird integration does not show up in the Integrations UI
Thank you
Marco
