### ISSUE TITLE
Scheduling?

### ISSUE THREAD

**Issue by luixal** [konikvranik/hacs_rainbird#4]
Hi!

I've been playing around with the module an it seem to work perfectly, on doubt: whta's the difference with the official add-on?

About scheduling, I'm wondering if I set an schedule in the rainbird device itself, does it keep working once it's configured in HA?

Thanks!

**Comment by konikvranik** [comment]
It's continuing of the development of the original HA integration. I added GUI configuration and some other enhancements.

The integration starts the irrigation directly. It's the same as start irrigation manually in time. It's not queued in time after the scheduled irrigation.
