### ISSUE TITLE
available commands - broken link 

### ISSUE THREAD

**Issue by michapr** [konikvranik/hacs_rainbird#6]
Hi,

"Please see [commands in pyrainbird project](https://github.com/jbarrancos/pyrainbird/blob/master/pyrainbird/resources/sipcommands.json) for available commands"

-> 404

Could you provide the commands please?
Thanks!

**Comment by konikvranik** [comment]
Fixed. Thank you for your report.

**Comment by konikvranik** [comment]
Fixed. Thank you for your report.

**Comment by konikvranik** [comment]
Fixed. Thank you for your report.
