### ISSUE TITLE
User input malformed: expected dict for dictionary value @ data['scan_interval']

### ISSUE THREAD

**Issue by luixal** [konikvranik/hacs_rainbird#7]
Hi,

After installing from HACS, once I'm configuring the integration, I set my rainbirds ip as hostname the password and other data but I get this error message (cant upload screenshot, don't know why):

```
User input malformed: expected dict for dictionary value @ data['scan_interval']
```

Any what can be wrong? I'm not seeing anything in the logs.

Thanks!

**Comment by plouf34** [comment]
Hello
Same for me

**Comment by konikvranik** [comment]
What value do you have for scan interval?

**Comment by luixal** [comment]
That was it. The "Sensor update period" by default is set to 00h00m00s and I had left as it was. Once I set it to 5 seconds, it worked out and configured the integration successfully.

Anyhow, It didn't got configured successfully, I got and "UNKOWN MODEL" device and only a Rainsensor. Thing is, I have no rainsensor configured (although my rainbird device supports it) but what I do have are 8 irrigation zones and none got auto detected (the core integration does find them).

Any idea on what to do?

**UPDATE**: I re-configured the integration setting the number of zones (8 in my case) instead of leaving 0 for it to find them. It took some time (don't know why) and they finally appeared but... they do **not** work at all. Kind of weird because if I use the core rainbird integration it works just fine. I think there's something broken here.

Thanks for your work.

**Comment by konikvranik** [comment]
Hi @luixal, it's common that finding of model and proper zones takes some time. It calls the Rainbird controller asynchronously to get all the information.

But then it should work. Is there some error or warning in the logs? What does it means that they don't work? Switches are available but not enabling the irrigation? Or switches are missing? Or are they there but disabled?

**Comment by luixal** [comment]
Hi,

Yes, it took some time to get the zones but always once I've set to 8 the number of zones in the devices. If I left it at 0 for auto-detection, none was found. Also, those 8 zones which took some time to be found, won't turn on/off the sprinklers.

Didn't see anything in the logs, I just went back to the core integration as I needed to get it working.

If you need me to test something, just tell me and I can try it out.

**Comment by konikvranik** [comment]
Now it should be fixed. Zones auto-detection and irrigation now works for me. @luixal: please update the integration and check by yourself.
