### ISSUE TITLE
Where to add rainbird controller

### ISSUE THREAD

**Issue by anyth1n9** [konikvranik/hacs_rainbird#8]
Hi,

I've installed the hacs_rainbird integration and removed the rainbird code in the configuration.yaml file.
However I can't find where I can add the rainbird controller. I changed to this integration because the home assistant approved one doesn't seem to work anymore

**Comment by konikvranik** [comment]
Hello,

if you install hacs_rainbird into custom integrations, then you can add new Rainbird controlled using Home assistant UI. Just add new integration searching rainbird.

**Comment by anyth1n9** [comment]
Hi,
Thanks for the reply. I will try!
