### ISSUE TITLE
 cannot add multiple Rainbird controllers

### ISSUE THREAD

**Issue by kotana** [konikvranik/hacs_rainbird#9]
Hello,

it is not possible to integrate two controllers.
I have two ESP-RZXes, one with 6 zones and one with 4 zones.
Two different IP addresses and the same password.
It finds both controllers but only takes one and overwrites the values.

![image](https://user-images.githubusercontent.com/760382/165273726-e13008f8-c69a-42f6-b1f6-e50330261dff.png)
![image](https://user-images.githubusercontent.com/760382/165273800-014cea8f-d0ab-46bd-9938-ba16016f05a3.png)

**Comment by WojtekK78** [comment]
Not solution but crude workaround. Copy what you have in "custom_components/rainbird" to new folder i.e. "custom_components/rainbird2" and within that folder change in manifest.json domain to i.e "rainbird2" I've also changed name but that may not be needed.
Than after restart you will have rainbird2 also visible in integration and you can setup your second controller that way.
Crude but working.

**Comment by konikvranik** [comment]
It would be nice if someone with multiple controllers could debug and fix this.

**Comment by tonydesigns85** [comment]
Hello, I was using the rainbird integration and is asking me for the host host name for rainbird controller where would I find this? I thought it would be the iP address but that is not working.  Where would I be able to find it?

**Comment by konikvranik** [comment]
Hi @tonydesigns85,

 there is no reason that IP shouldn't work.
You can put DNS name here or IP. What you put here is then used to construct URL: `requests.post( "http://%s/stick" % self.rainbird_server,...)`.
Doble check that you use right IP and whether the URL is accessible on your network.

**Comment by tonydesigns85** [comment]
Thank you for the quick responds I was able to figure it out.  The wifi device that I connected it to was not working properly so I connected it to another network got the IP from there and it started to work thank you.

**Comment by kotana** [comment]
please fix multiple controllers!!!!

**Comment by kotana** [comment]
Hi, everyone ,

is there no further development for the addon?

**Comment by konikvranik** [comment]
Currently there is no need for changes from my side.
You are free to contribute and provide PR with support for two controllers.
I have just single one, so I'm not capable to test it.
